### ISSUE TITLE
V2 - legacy branch request

### ISSUE THREAD

**Issue by Adrion** [initbiz/oc-cumuluscore-plugin#26]
Hi, 
My project is using oc-bootstraper and install listed plugins. 
Since I can't migrate right now to v3 my project just broke...

As oc-boostraper allow custom branch fetch can you push a v2 legacy branch ?
I would prefer this over making a fork. 😄

Thanks !

**Comment by tomaszstrojny** [comment]
Hi,

Sure, but only for you :smile: 

It's created: `v2-legacy`, but keep in mind it's not going to be updated and this applies to other Cumulus extensions as well. They're not going to be compatible with v2.

**Comment by Adrion** [comment]
Thanks no problem ! 
I will be able to migrate more serenely :)

**Comment by Adrion** [comment]
Many thanks for this, I don't need it anymore. 
You can safely delete it if needed :)
