### ISSUE TITLE
Php Error

### ISSUE THREAD

**Issue by chrisvidal** [initbiz/oc-cumuluscore-plugin#30]
my setup is an `index.htm`

```yaml
title = "Homepage"
url = "/"
layout = "default"
is_hidden = 0

[session]
security = "all"

[account]
redirect = "system/choose-cluster"
paramCode = "code"
forceSecure = 0
==

{% component 'account' %}
```

and I receive this error:

```php
Call to a member function canEnterFeature() on null
/Users/christophevidal/Sites/oc-dronet/plugins/initbiz/cumuluscore/classes/MenuManager.php line 37
```

**Comment by tomaszstrojny** [comment]
Provide the stacktrace, please.

**Comment by chrisvidal** [comment]
I put it just previously.

the rest is the code

```php
//If $itemFeatures empty, then foreach will not run
                foreach ($itemFeatures as $featureCode) {
                    //If any cumulusFeature exists than hide the item
                    $item->viewBag['isHidden'] = "1";
                    if ($cluster->canEnterFeature($featureCode)) {
                        //The item will be shown only when cluster has access to feature
                        $item->viewBag['isHidden'] = "0";
                        break;
                    }
                }
                if ($item->items) {
```

**Comment by tomaszstrojny** [comment]
It's pretty short for the full stack trace. It just looks like you have not pasted all the things you have there.

What I mean is that `MenuManager` is used only for the menus that are created with the help of `RainLab.Pages` plugin. It seems you have the menu also embedded on the page.

All in all, that's the case I haven't expected. We have a user and static menu but we don't have a cluster defined yet. Update the plugin and ping me if it's still failing.

**Comment by chrisvidal** [comment]
there has been no update avaialble since the last4 days on my side

still Cumulus 3.2.2

**Comment by tomaszstrojny** [comment]
Oh, I assumed that you use the Git version and haven't published a new version in the marketplace.

It's published now :)

**Comment by chrisvidal** [comment]
hehe :)
ok thanks, I managed to upgrade.

Now I have another error:

my user is not attache to any cluster.
I have a menu linked to a set of cumulus pages.

this user still can see the menu links. which he should not be able to normally.

**Comment by tomaszstrojny** [comment]
"It's not a bug, it's a feature" :D

That's exactly why the error occurred. Overriding the menu by Cumulus works that way. It only filters the items that the user does not have access to.

What's your use case? Why have you decided to keep users that are not assigned to any clusters while sill have access to pages with the cumulus filtered nav?

**Comment by chrisvidal** [comment]
I don't have this scenario, it was just a feedback from my current setup :)

however, now I attached my user to a cluster.
I have a menu attached to cumulus page.

After login, my user is automatically redirected to this page `http://oc-dronet.local/voilaah/dashboard` which is intended. `Voilaah` is the cluster name

the menu display the wrong url.
all the menu links are not having the cluster name in the link, example for dashboard:

`http://oc-dronet.local/dashboard`

and it should be 

`http://oc-dronet.local/voilaah/dashboard`

**Comment by tomaszstrojny** [comment]
Add `cluster` variable to your page's URL like so: `/:cluster/dashboard`.

**Comment by chrisvidal** [comment]
well the menu is build by the staticMenu component, so how can I do that?

**Comment by tomaszstrojny** [comment]
The first thing to do is to use "Cumulus page" in the menu item:
![image](https://user-images.githubusercontent.com/8854428/78016341-f5fd1700-734a-11ea-8bfa-39096350fda8.png)

The second is to add the parameter to your CMS page:
![image](https://user-images.githubusercontent.com/8854428/78016435-16c56c80-734b-11ea-900f-6eba732fc345.png)

**Comment by chrisvidal** [comment]
oh I see , hence I don't need to do any coding...ok let me try tomorrow and let you know

thanks for your help :) appreciate

**Comment by chrisvidal** [comment]
thanks, it seems to work.

It stops working as soon as the `:cluster` is not anymore in the url which can be a problem I think.

Does your component set up a page variable named `cluster` that would be available in our theme?

**Comment by tomaszstrojny** [comment]
I hit the page by accident and see you have asked a question... I have no idea why I didn't get any e-mail for it.

The `CumulusGuard` component does it, yes :)

**Comment by chrisvidal** [comment]
thanks
